# Generated by Django 4.2 on 2024-08-23 14:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='icons/default_icon.png', null=True, upload_to='icons/')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
        ),
    ]
