# Generated by Django 4.2 on 2024-08-24 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_newscategory_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='pulished',
            new_name='published',
        ),
    ]
