# Generated by Django 4.2 on 2024-08-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_rename_pulished_news_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='viewers',
            field=models.PositiveIntegerField(default=1294),
        ),
    ]
