# Generated by Django 4.2 on 2024-08-24 05:58

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_news_viewers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=256)),
                ('title_uz', models.CharField(max_length=256, null=True)),
                ('title_ru', models.CharField(max_length=256, null=True)),
                ('title_en', models.CharField(max_length=256, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('created', models.DateTimeField()),
                ('alias', models.CharField(max_length=256, unique=True)),
                ('published', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.newscategory')),
            ],
        ),
    ]
