# Generated by Django 4.2 on 2024-08-24 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='category',
        ),
        migrations.RemoveField(
            model_name='info',
            name='created',
        ),
        migrations.RemoveField(
            model_name='info',
            name='published',
        ),
    ]
