# Generated by Django 4.2 on 2024-08-24 07:12

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_doc_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='created',
            field=models.DateTimeField(default=datetime.now),
            preserve_default=False,
        ),
    ]
