# Generated by Django 4.2 on 2024-09-01 11:32

import clinic.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_doc_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', validators=[clinic.validators.validate_image_size])),
            ],
        ),
    ]
