# Generated by Django 4.2 on 2024-09-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
