# Generated by Django 4.2 on 2024-09-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_alter_news_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doc',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uz',
            field=models.TextField(null=True),
        ),
    ]
